# Generated by Django 4.2.16 on 2025-01-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0111_alter_campaña_activa_alter_desafio_activada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='tematica',
            field=models.ManyToManyField(blank=True, max_length=10, null=True, related_name='Tema', to='social.tematica'),
        ),
    ]
