# Generated by Django 4.2.16 on 2025-01-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0112_alter_comunidad_tematica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
