# Generated by Django 4.2.16 on 2025-02-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0113_alter_campaña_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='activada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='activada',
            field=models.BooleanField(default=False),
        ),
    ]
